"""Bearer-token auth and local audit helpers for the profile router.

The ChatGPT ↔ Hermes profile router v1 is self-hosted/local by default.  When
served over HTTP it uses personal bearer tokens generated by Hermes, stores only
server-side hashes, and writes a small local JSONL audit log.  This module is
kept independent from the Hermes agent loop and never calls any model path.
"""

from __future__ import annotations

import hashlib
import hmac
import json
import os
import secrets
import tempfile
import time
from contextlib import contextmanager
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable, Mapping
from uuid import uuid4

from hermes_constants import get_hermes_home

DEFAULT_PROFILE_ROUTER_SCOPES = ("context:read", "workspace:read", "diff:read")
PROFILE_ROUTER_WRITE_SCOPE = "workspace:write"
PROFILE_ROUTER_TERMINAL_SCOPE = "terminal:run"
PROFILE_ROUTER_CRON_SCOPE = "cron:manage"
PROFILE_ROUTER_MESSAGING_SCOPE = "messaging:send"
VIKING_PROFILE_ROUTER_SCOPE = "viking:read"
SUPPORTED_PROFILE_ROUTER_SCOPES = (
    *DEFAULT_PROFILE_ROUTER_SCOPES,
    PROFILE_ROUTER_WRITE_SCOPE,
    PROFILE_ROUTER_TERMINAL_SCOPE,
    PROFILE_ROUTER_CRON_SCOPE,
    PROFILE_ROUTER_MESSAGING_SCOPE,
    VIKING_PROFILE_ROUTER_SCOPE,
)
PROFILE_ROUTER_TOKEN_FILENAME = "profile_router_tokens.json"
PROFILE_ROUTER_AUDIT_FILENAME = "profile_router_audit.jsonl"
TOKEN_PREFIX = "hpr"
TOKEN_HASH_PREFIX = "sha256:"
TOKEN_ID_PREFIX = "prt"
TOKEN_ID_BYTES = 9
TOKEN_SECRET_BYTES = 32
TOKEN_STORE_LOCK_TIMEOUT_SECONDS = 5.0
TOKEN_STORE_LOCK_STALE_SECONDS = 60.0


class ProfileRouterAuthError(ValueError):
    """Raised when profile-router bearer token auth fails."""

    def __init__(self, code: str, message: str):
        super().__init__(message)
        self.code = code
        self.message = message


@dataclass(frozen=True)
class ProfileRouterTokenVerification:
    """Sanitized result of verifying a profile-router bearer token."""

    token_id: str
    token_hash: str
    scopes: tuple[str, ...]
    expires_at: str | None = None

    @property
    def token_hash_prefix(self) -> str:
        return self.token_hash[: len(TOKEN_HASH_PREFIX) + 16]

    @property
    def expires_at_unix(self) -> int | None:
        if not self.expires_at:
            return None
        parsed = _parse_timestamp(self.expires_at, field="expires_at")
        return int(parsed.timestamp())


@dataclass(frozen=True)
class _FallbackAccessToken:
    """Small AccessToken stand-in for tests when the optional MCP SDK is absent."""

    token: str
    client_id: str
    scopes: list[str]
    expires_at: int | None = None

    def model_dump(self) -> dict[str, Any]:
        return {
            "token": self.token,
            "client_id": self.client_id,
            "scopes": self.scopes,
            "expires_at": self.expires_at,
        }


def _access_token_class():
    try:
        from mcp.server.auth.provider import AccessToken
    except ImportError:
        return _FallbackAccessToken
    return AccessToken


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _now_iso() -> str:
    return _now().isoformat(timespec="seconds")


def _parse_timestamp(value: str, *, field: str) -> datetime:
    if not isinstance(value, str) or not value.strip():
        raise ProfileRouterAuthError("invalid_timestamp", f"{field} must be an ISO timestamp")
    text = value.strip()
    if text.endswith("Z"):
        text = text[:-1] + "+00:00"
    try:
        parsed = datetime.fromisoformat(text)
    except ValueError as exc:
        raise ProfileRouterAuthError("invalid_timestamp", f"{field} must be an ISO timestamp") from exc
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc)


def _default_token_store_path() -> Path:
    return get_hermes_home() / PROFILE_ROUTER_TOKEN_FILENAME


def _default_audit_log_path() -> Path:
    return get_hermes_home() / PROFILE_ROUTER_AUDIT_FILENAME


def _chmod_private(path: Path) -> None:
    try:
        path.chmod(0o600)
    except OSError:
        # Best effort on filesystems/platforms without POSIX modes.
        pass


def _atomic_write_json(path: Path, payload: Mapping[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".tmp", dir=str(path.parent))
    tmp_path = Path(tmp_name)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            json.dump(payload, handle, indent=2, sort_keys=True)
            handle.write("\n")
        _chmod_private(tmp_path)
        os.replace(tmp_path, path)
        _chmod_private(path)
    finally:
        try:
            tmp_path.unlink(missing_ok=True)
        except OSError:
            pass


def _token_hash(token: str) -> str:
    digest = hashlib.sha256(token.encode("utf-8")).hexdigest()
    return TOKEN_HASH_PREFIX + digest


def _new_token_id() -> str:
    return f"{TOKEN_ID_PREFIX}_{secrets.token_urlsafe(TOKEN_ID_BYTES).replace('-', '_')}"


def _normalize_scopes(scopes: Iterable[str] | None) -> tuple[str, ...]:
    values = list(DEFAULT_PROFILE_ROUTER_SCOPES if scopes is None else scopes)
    normalized: list[str] = []
    for scope in values:
        if not isinstance(scope, str):
            raise ProfileRouterAuthError("invalid_scope", "scopes must be strings")
        text = scope.strip()
        if not text:
            continue
        if text not in SUPPORTED_PROFILE_ROUTER_SCOPES:
            raise ProfileRouterAuthError(
                "invalid_scope",
                "Unsupported profile-router scope: " + text,
            )
        if text not in normalized:
            normalized.append(text)
    if not normalized:
        raise ProfileRouterAuthError("invalid_scope", "at least one scope is required")
    return tuple(normalized)


def _safe_record(record: Mapping[str, Any]) -> dict[str, Any]:
    token_hash = str(record.get("token_hash") or "")
    return {
        "token_id": record.get("token_id"),
        "name": record.get("name") or "",
        "scopes": list(record.get("scopes") or []),
        "created_at": record.get("created_at"),
        "last_used_at": record.get("last_used_at"),
        "revoked_at": record.get("revoked_at"),
        "expires_at": record.get("expires_at"),
        "token_hash_prefix": token_hash[: len(TOKEN_HASH_PREFIX) + 16] if token_hash else "",
    }


class ProfileRouterTokenStore:
    """Hash-only token store for local profile-router bearer tokens."""

    def __init__(self, path: str | Path | None = None):
        self.path = Path(path) if path is not None else _default_token_store_path()
        self._lock_depth = 0

    @property
    def _lock_path(self) -> Path:
        return self.path.with_name(f"{self.path.name}.lock")

    @contextmanager
    def _locked_store(self):
        """Serialize token-store read/modify/write across server and CLI processes."""

        if self._lock_depth:
            yield
            return

        self.path.parent.mkdir(parents=True, exist_ok=True)
        lock_path = self._lock_path
        deadline = time.monotonic() + TOKEN_STORE_LOCK_TIMEOUT_SECONDS
        fd: int | None = None
        while True:
            try:
                fd = os.open(lock_path, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o600)
                os.write(fd, f"pid={os.getpid()} created_at={_now_iso()}\n".encode("utf-8"))
                _chmod_private(lock_path)
                break
            except FileExistsError:
                try:
                    age_seconds = time.time() - lock_path.stat().st_mtime
                    if age_seconds > TOKEN_STORE_LOCK_STALE_SECONDS:
                        lock_path.unlink()
                        continue
                except FileNotFoundError:
                    continue
                except OSError:
                    pass
                if time.monotonic() >= deadline:
                    raise ProfileRouterAuthError(
                        "token_store_locked",
                        "profile-router token store is locked by another process",
                    )
                time.sleep(0.02)
            except OSError as exc:
                raise ProfileRouterAuthError(
                    "token_store_lock_failed",
                    "profile-router token store lock could not be acquired",
                ) from exc

        self._lock_depth += 1
        try:
            yield
        finally:
            self._lock_depth -= 1
            if fd is not None:
                try:
                    os.close(fd)
                except OSError:
                    pass
            try:
                lock_path.unlink()
            except FileNotFoundError:
                pass
            except OSError:
                pass

    def _load(self) -> dict[str, Any]:
        if not self.path.exists():
            return {"version": 1, "tokens": []}
        try:
            with self.path.open("r", encoding="utf-8") as handle:
                data = json.load(handle)
        except json.JSONDecodeError as exc:
            raise ProfileRouterAuthError("token_store_invalid", "profile-router token store is not valid JSON") from exc
        except OSError as exc:
            raise ProfileRouterAuthError("token_store_unreadable", "profile-router token store is not readable") from exc
        if not isinstance(data, dict):
            raise ProfileRouterAuthError("token_store_invalid", "profile-router token store must be an object")
        tokens = data.get("tokens")
        if tokens is None:
            data["tokens"] = []
        elif not isinstance(tokens, list):
            raise ProfileRouterAuthError("token_store_invalid", "profile-router token store tokens must be a list")
        return data

    def _save(self, data: Mapping[str, Any]) -> None:
        _atomic_write_json(self.path, data)

    def create_token(
        self,
        *,
        scopes: Iterable[str] | None = None,
        name: str = "",
        expires_at: str | None = None,
    ) -> dict[str, Any]:
        """Create one strong bearer token and persist only its hash."""

        normalized_scopes = _normalize_scopes(scopes)
        normalized_expires_at = None
        if expires_at:
            normalized_expires_at = _parse_timestamp(expires_at, field="expires_at").isoformat(
                timespec="seconds"
            )
        token_id = _new_token_id()
        secret = secrets.token_urlsafe(TOKEN_SECRET_BYTES)
        token = f"{TOKEN_PREFIX}_{token_id}_{secret}"
        record = {
            "token_id": token_id,
            "name": str(name or "").strip(),
            "token_hash": _token_hash(token),
            "scopes": list(normalized_scopes),
            "created_at": _now_iso(),
            "last_used_at": None,
            "revoked_at": None,
            "expires_at": normalized_expires_at,
        }
        with self._locked_store():
            data = self._load()
            data.setdefault("tokens", []).append(record)
            self._save(data)
        return {"token": token, "record": _safe_record(record)}

    def list_tokens(self, *, include_revoked: bool = True) -> list[dict[str, Any]]:
        with self._locked_store():
            data = self._load()
            records = []
            for record in data.get("tokens", []):
                if not isinstance(record, Mapping):
                    continue
                if not include_revoked and record.get("revoked_at"):
                    continue
                records.append(_safe_record(record))
            return records

    def revoke_token(self, token_id: str) -> dict[str, Any]:
        token_id = str(token_id or "").strip()
        if not token_id:
            raise ProfileRouterAuthError("invalid_token_id", "token_id is required")
        with self._locked_store():
            data = self._load()
            for record in data.get("tokens", []):
                if isinstance(record, dict) and record.get("token_id") == token_id:
                    if not record.get("revoked_at"):
                        record["revoked_at"] = _now_iso()
                        self._save(data)
                    return _safe_record(record)
        raise ProfileRouterAuthError("token_not_found", f"profile-router token not found: {token_id}")

    def rotate_token(self, token_id: str) -> dict[str, Any]:
        token_id = str(token_id or "").strip()
        if not token_id:
            raise ProfileRouterAuthError("invalid_token_id", "token_id is required")
        with self._locked_store():
            data = self._load()
            selected: Mapping[str, Any] | None = None
            for record in data.get("tokens", []):
                if isinstance(record, dict) and record.get("token_id") == token_id:
                    selected = dict(record)
                    if not record.get("revoked_at"):
                        record["revoked_at"] = _now_iso()
                    break
            if selected is None:
                raise ProfileRouterAuthError("token_not_found", f"profile-router token not found: {token_id}")
            self._save(data)
            return self.create_token(
                scopes=selected.get("scopes") or DEFAULT_PROFILE_ROUTER_SCOPES,
                name=selected.get("name") or "",
                expires_at=selected.get("expires_at"),
            )

    def verify_token(
        self,
        token: str,
        *,
        required_scopes: Iterable[str] | None = None,
    ) -> ProfileRouterTokenVerification | None:
        if not isinstance(token, str) or not token.strip():
            return None
        digest = _token_hash(token.strip())
        now = _now()
        required = set(_normalize_scopes(required_scopes or ())) if required_scopes else set()
        with self._locked_store():
            data = self._load()
            matched_record: dict[str, Any] | None = None
            for record in data.get("tokens", []):
                if not isinstance(record, dict):
                    continue
                stored_hash = str(record.get("token_hash") or "")
                if not hmac.compare_digest(stored_hash, digest):
                    continue
                matched_record = record
                break
            if matched_record is None:
                return None
            if matched_record.get("revoked_at"):
                return None
            expires_at = matched_record.get("expires_at")
            if expires_at and _parse_timestamp(str(expires_at), field="expires_at") <= now:
                return None
            scopes = tuple(str(scope) for scope in matched_record.get("scopes") or [])
            if required and not required.issubset(set(scopes)):
                return None
            matched_record["last_used_at"] = _now_iso()
            self._save(data)
            return ProfileRouterTokenVerification(
                token_id=str(matched_record.get("token_id") or ""),
                token_hash=digest,
                scopes=scopes,
                expires_at=str(expires_at) if expires_at else None,
            )


class ProfileRouterBearerTokenVerifier:
    """MCP SDK token verifier backed by ``ProfileRouterTokenStore``."""

    def __init__(self, store: ProfileRouterTokenStore | None = None):
        self.store = store or ProfileRouterTokenStore()

    async def verify_token(self, token: str):
        verified = self.store.verify_token(token)
        if verified is None:
            return None
        AccessToken = _access_token_class()

        # ``token`` in the AccessToken context deliberately carries only a hash
        # prefix, never the raw bearer token.
        return AccessToken(
            token=verified.token_hash_prefix,
            client_id=verified.token_id,
            scopes=list(verified.scopes),
            expires_at=verified.expires_at_unix,
        )


class ProfileRouterAuditLogger:
    """Append-only local JSONL audit log with secret-safe fields only."""

    def __init__(self, path: str | Path | None = None):
        self.path = Path(path) if path is not None else _default_audit_log_path()

    def append(self, entry: Mapping[str, Any]) -> None:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        sanitized = {
            "request_id": entry.get("request_id") or f"req_{uuid4().hex}",
            "timestamp": entry.get("timestamp") or _now_iso(),
            "token_id": entry.get("token_id"),
            "token_hash_prefix": entry.get("token_hash_prefix"),
            "profile": entry.get("profile"),
            "workspace_id": entry.get("workspace_id"),
            "tool": entry.get("tool"),
            "scope": entry.get("scope"),
            "ok": bool(entry.get("ok")),
            "error": entry.get("error"),
            "llm_calls": int(entry.get("llm_calls") or 0),
            "bytes": entry.get("bytes") if isinstance(entry.get("bytes"), int) else None,
            "truncated": bool(entry.get("truncated")),
        }
        try:
            with self.path.open("a", encoding="utf-8") as handle:
                handle.write(json.dumps(sanitized, sort_keys=True) + "\n")
            _chmod_private(self.path)
        except OSError as exc:
            raise ProfileRouterAuthError("audit_log_unwritable", "profile-router audit log is not writable") from exc


def current_access_token_identity() -> dict[str, str | None]:
    """Return sanitized MCP auth identity for the current request, if any."""

    try:
        from mcp.server.auth.middleware.auth_context import get_access_token
    except Exception:
        return {"token_id": None, "token_hash_prefix": None}
    token = get_access_token()
    if token is None:
        return {"token_id": None, "token_hash_prefix": None}
    return {"token_id": token.client_id, "token_hash_prefix": token.token}


def current_access_token_has_scope(scope: str) -> bool:
    try:
        from mcp.server.auth.middleware.auth_context import get_access_token
    except Exception:
        return False
    token = get_access_token()
    return bool(token and scope in set(token.scopes or []))


def require_current_access_token_scope(scope: str) -> dict[str, str | None]:
    identity = current_access_token_identity()
    if not identity.get("token_id"):
        raise ProfileRouterAuthError("auth_required", "profile-router HTTP tools require a bearer token")
    if not current_access_token_has_scope(scope):
        raise ProfileRouterAuthError("insufficient_scope", f"profile-router token requires scope: {scope}")
    return identity


def extract_result_audit_fields(result: str) -> dict[str, Any]:
    """Extract small audit fields from a JSON tool response without raw content."""

    bytes_len = len(result.encode("utf-8", errors="replace"))
    payload: Any
    try:
        payload = json.loads(result)
    except json.JSONDecodeError:
        return {"ok": False, "error": "invalid_json_result", "llm_calls": 0, "bytes": bytes_len, "truncated": True}
    if not isinstance(payload, Mapping):
        return {"ok": False, "error": "invalid_result", "llm_calls": 0, "bytes": bytes_len, "truncated": True}

    def _find_truncated(value: Any) -> bool:
        if isinstance(value, Mapping):
            if value.get("truncated") is True or value.get("stdout_truncated") is True or value.get("stderr_truncated") is True:
                return True
            return any(_find_truncated(item) for item in value.values())
        if isinstance(value, list):
            return any(_find_truncated(item) for item in value)
        return False

    error = None
    if isinstance(payload.get("error"), Mapping):
        error = payload["error"].get("code")
    return {
        "ok": bool(payload.get("ok")),
        "error": error,
        "llm_calls": int(payload.get("llm_calls") or 0),
        "bytes": bytes_len,
        "truncated": _find_truncated(payload),
    }
