"""Gateway response filtering helpers.

These helpers operate at the gateway boundary: they decide whether a completed
agent turn should be delivered to the chat, not what should be persisted in the
conversation history.
"""

from __future__ import annotations

from typing import Any

# Canonical model-emitted control token for intentional silence.
SILENT_REPLY_TOKEN = "NO_REPLY"

# Discord can surface attachment/unsupported/deleted-message shells through the
# gateway as a literal placeholder string instead of an empty body.  Treat this
# as empty at the dispatch boundary; otherwise it starts a full agent turn and
# can keep shutdown/restart drains alive with meaningless work.
EMPTY_INBOUND_TEXT_SENTINELS = frozenset({
    "(The user sent a message with no text content)",
})

# Exact whole-response markers that mean "the agent intentionally chose not to
# reply".  Keep this list small and explicit; arbitrary empty output remains an
# error/empty-response path, not silence.
LIVE_GATEWAY_SILENT_MARKERS = frozenset({
    "[SILENT]",
    "SILENT",
    "NO_REPLY",
    "NO REPLY",
})


def _canonical_silence_candidate(text: str) -> str:
    return " ".join(text.strip().upper().split())


def _is_verifier_receipt_response(text: str) -> bool:
    """Return True for delivery-only receipts generated by edit verification.

    The edit verifier can appear as a synthetic user turn asking for a temp
    ``hermes-verify-*`` script.  The agent must satisfy that internally, but the
    resulting boilerplate receipt is control-plane plumbing, not useful chat
    content for the user.  Keep this narrow: suppress only messages that look
    like a pure verifier receipt with temp-script/cleanup evidence.
    """
    stripped = text.strip()
    lowered = stripped.lower()
    if not stripped:
        return False
    verifier_markers = (
        "ad-hoc verifier passed",
        "ad-hoc verification passed",
        "this is **ad-hoc verification**",
        "this is ad-hoc verification",
    )
    has_verifier_marker = any(marker in lowered for marker in verifier_markers)
    has_temp_script = "hermes-verify-" in lowered or "/var/folders/" in lowered
    has_cleanup = "cleanup" in lowered and "removed" in lowered
    if not (has_verifier_marker and has_temp_script and has_cleanup):
        return False

    # Do not suppress a substantive user-facing update that happens to include
    # a verification note. Pure receipts are typically short checklists.
    allowed_prefixes = (
        "ad-hoc verifier passed",
        "ad-hoc verification passed",
    )
    return lowered.startswith(allowed_prefixes)


def should_drop_empty_inbound_event(event: Any) -> bool:
    """Return True for user-originated empty events that should not start a turn.

    Some platforms can emit text updates with no body (for example topic/router
    artifacts or deleted/unsupported payload shells). Letting those through to
    the agent creates useless "blank message" replies and can loop across
    mirrored chats. Keep the predicate conservative: internal synthetic events,
    media/file payloads, and reply-context events still flow.
    """
    if bool(getattr(event, "internal", False)):
        return False
    text = getattr(event, "text", "")
    if not isinstance(text, str):
        return False
    stripped = text.strip()
    if stripped and stripped not in EMPTY_INBOUND_TEXT_SENTINELS:
        return False

    if getattr(event, "media_urls", None):
        return False
    if getattr(event, "media_types", None):
        return False
    if getattr(event, "reply_to_text", None):
        return False

    return True


def is_intentional_silence_response(response: Any) -> bool:
    """Return True only for explicit or control-plane silence.

    Substantive prose that merely mentions ``NO_REPLY`` or ``[SILENT]`` must be
    delivered normally.  A blank response is also not silence; blank output is
    handled by the empty-response failure path.
    """
    if not isinstance(response, str):
        return False
    stripped = response.strip()
    if not stripped:
        return False
    if _is_verifier_receipt_response(stripped):
        return True
    if len(stripped) > 64:
        return False
    return _canonical_silence_candidate(stripped) in LIVE_GATEWAY_SILENT_MARKERS


def is_intentional_silence_agent_result(agent_result: dict | None, response: Any) -> bool:
    """Silence markers suppress delivery only for successful agent turns."""
    if not isinstance(agent_result, dict):
        return False
    if agent_result.get("failed"):
        return False
    return is_intentional_silence_response(response)


def is_partial_silence_marker(text: Any) -> bool:
    """Return True while ``text`` could still resolve to a silence marker.

    The streaming path accumulates the reply delta-by-delta and must decide,
    before the whole response is known, whether to show what it has so far.
    A buffer whose canonical form is a non-empty *prefix* of a silence marker
    (e.g. ``"NO"`` on the way to ``"NO_REPLY"``, or an exact marker that has
    not yet been terminated by stream-end) is held back so a raw marker is
    never edited onto the screen and then belatedly retracted.

    Anything that has already diverged from every marker (ordinary prose) —
    and anything longer than the marker cap — returns False so normal
    streaming resumes immediately.  This is the streaming counterpart to
    :func:`is_intentional_silence_response`, sharing the same marker set and
    canonicalization so the two never drift.
    """
    if not isinstance(text, str):
        return False
    stripped = text.strip()
    if not stripped or len(stripped) > 64:
        return False
    candidate = _canonical_silence_candidate(stripped)
    if not candidate:
        return False
    return any(marker.startswith(candidate) for marker in LIVE_GATEWAY_SILENT_MARKERS)
