#!/usr/bin/env python3
"""
AI Detection Test Script for Documents
Tests text against both RoBERTa classification and GPT-2 perplexity.

Usage:
  python3 detect_test.py document.pdf
  python3 detect_test.py document.docx
  python3 detect_test.py "paste text here"

Requires: pip install transformers torch 'numpy<2' pymupdf python-docx
"""

import sys
import os
import math
import warnings

warnings.filterwarnings('ignore')


def extract_text(path):
    """Extract text from PDF, DOCX, or raw text string."""
    if not os.path.isfile(path):
        return path  # Treat as raw text

    ext = os.path.splitext(path)[1].lower()

    if ext == '.pdf':
        import pymupdf
        doc = pymupdf.open(path)
        text = ''
        for page in doc:
            text += page.get_text() + '\n'
        doc.close()
        return text.strip()

    elif ext in ('.docx', '.doc'):
        from docx import Document
        doc = Document(path)
        return '\n'.join(p.text for p in doc.paragraphs if p.text.strip())

    else:
        with open(path, 'r') as f:
            return f.read()


def check_unicode_dashes(text):
    """Check for AI-typical unicode dashes."""
    em_count = text.count('\u2014')
    en_count = text.count('\u2013')
    double_dash = text.count('--')
    return em_count, en_count, double_dash


def check_metadata(path):
    """Check file metadata for AI generation fingerprints."""
    issues = []

    if not os.path.isfile(path):
        return issues  # Can't check metadata for raw text

    ext = os.path.splitext(path)[1].lower()

    if ext == '.pdf':
        import pymupdf
        doc = pymupdf.open(path)
        meta = doc.metadata
        if meta.get('producer', ''):
            issues.append(f"PDF producer field not empty: '{meta.get('producer')}'")
        if 'python' in meta.get('creator', '').lower():
            issues.append(f"PDF creator looks like Python library: '{meta.get('creator')}'")
        if 'fpdf' in meta.get('producer', '').lower() or 'fpdf' in meta.get('creator', '').lower():
            issues.append("PDF contains fpdf fingerprint")

        doc.close()

        # Binary scan
        with open(path, 'rb') as f:
            binary = f.read().lower()
        for keyword in ['python', 'fpdf', 'reportlab', 'pymupdf', 'fitz', 'pillow']:
            if keyword.encode() in binary:
                issues.append(f"Binary contains '{keyword}'")

    elif ext == '.docx':
        import zipfile
        from lxml import etree

        EP = 'http://schemas.openxmlformats.org/officeDocument/2006/extended-properties'
        CP = 'http://schemas.openxmlformats.org/package/2006/metadata/core-properties'

        zf = zipfile.ZipFile(path)

        # Check app.xml
        app_data = zf.read('docProps/app.xml')
        app_root = etree.fromstring(app_data)
        app_el = app_root.find(f'{{{EP}}}Application')
        if app_el is not None and 'python' in app_el.text.lower():
            issues.append(f"DOCX Application = '{app_el.text}' (should be 'Microsoft Office Word')")

        # Check core.xml
        core_data = zf.read('docProps/core.xml')
        core_root = etree.fromstring(core_data)
        for desc in core_root.findall(f'{{{CP}}}description'):
            if desc.text and 'python' in desc.text.lower():
                issues.append(f"DOCX description contains: '{desc.text}'")

        # Binary scan
        for item in zf.infolist():
            try:
                raw = zf.read(item.filename).decode('utf-8', errors='ignore').lower()
                for keyword in ['python-docx', 'generated by python']:
                    if keyword in raw:
                        issues.append(f"Binary contains '{keyword}' in {item.filename}")
            except Exception:
                pass

        zf.close()

    return issues


def test_roberta(text):
    """Test with OpenAI RoBERTa detector. Returns (human_pct, ai_pct)."""
    try:
        from transformers import pipeline
        detector = pipeline("text-classification",
                            model="openai-community/roberta-base-openai-detector")

        # Test in chunks (512 token model limit)
        chunks = [text[i:i+1500] for i in range(0, len(text), 1500)]
        scores = []

        for chunk in chunks:
            if len(chunk.strip()) < 50:
                continue
            result = detector(chunk[:512], truncation=True)
            pred = result[0]
            human = pred['score'] * 100 if pred['label'] == 'REAL' else (1 - pred['score']) * 100
            scores.append(human)

        if scores:
            avg = sum(scores) / len(scores)
            return avg, 100 - avg
        return 50.0, 50.0
    except Exception:
        return None, None


def test_perplexity(text):
    """Test with GPT-2 perplexity. Returns average perplexity score."""
    try:
        from transformers import AutoModelForCausalLM, AutoTokenizer
        import torch

        tokenizer = AutoTokenizer.from_pretrained("gpt2")
        model = AutoModelForCausalLM.from_pretrained("gpt2")
        model.eval()

        # Test in chunks
        chunks = [text[i:i+1500] for i in range(0, len(text), 1500)]
        ppls = []

        for chunk in chunks:
            if len(chunk.strip()) < 50:
                continue
            enc = tokenizer(chunk[:512], return_tensors='pt', truncation=True, max_length=512)
            with torch.no_grad():
                loss = model(input_ids=enc['input_ids'], labels=enc['input_ids']).loss
            try:
                ppls.append(math.exp(loss.item()))
            except OverflowError:
                ppls.append(float('inf'))

        return sum(ppls) / len(ppls) if ppls else 0
    except Exception:
        return None


def classify_perplexity(ppl):
    """Classify perplexity score and give recommendation."""
    if ppl is None:
        return "CANNOT TEST", "Install: pip install transformers torch 'numpy<2'"

    if ppl < 20:
        return "VERY LIKELY AI", f"PPL={ppl:.1f} - Strongly AI-patterned"
    elif ppl < 40:
        return "LIKELY AI", f"PPL={ppl:.1f} - AI typical range"
    elif ppl < 60:
        return "BORDERLINE", f"PPL={ppl:.1f} - Could be human or AI"
    elif ppl < 80:
        return "PROBABLY HUMAN", f"PPL={ppl:.1f} - Human range (low end, ok for CVs)"
    elif ppl < 150:
        return "HUMAN", f"PPL={ppl:.1f} - Solidly human pattern"
    else:
        return "STRONGLY HUMAN", f"PPL={ppl:.1f} - Very varied/unpredictable"


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 detect_test.py <document.pdf|document.docx|\"text\">")
        sys.exit(1)

    input_arg = ' '.join(sys.argv[1:])

    print("=" * 60)
    print("  AI DETECTION TEST")
    print("=" * 60)

    # Extract text
    text = extract_text(input_arg)
    word_count = len(text.split())
    print(f"\n  Input: {input_arg[:60]}{'...' if len(input_arg) > 60 else ''}")
    print(f"  Words: {word_count}")

    # Unicode dash check
    em, en, dd = check_unicode_dashes(text)
    print(f"\n--- PUNCTUATION CHECK ---")
    if em > 0:
        print(f"  [FAIL] Em-dashes (\\u2014) found: {em} - REPLACE with ' - '")
    else:
        print(f"  [PASS] No em-dashes found")

    if en > 0:
        print(f"  [FAIL] En-dashes (\\u2013) found: {en} - REPLACE with '-'")
    else:
        print(f"  [PASS] No en-dashes found")

    if dd > 0:
        print(f"  [FAIL] Double hyphens (--) found: {dd} - REPLACE with ' - '")
    else:
        print(f"  [PASS] No double-hyphens found")

    # Metadata check
    if os.path.isfile(input_arg):
        print(f"\n--- METADATA CHECK ---")
        issues = check_metadata(input_arg)
        if issues:
            for issue in issues:
                print(f"  [FAIL] {issue}")
        else:
            print(f"  [PASS] No AI fingerprints in metadata")

    # GPT-2 Perplexity
    print(f"\n--- PERPLEXITY TEST (GPT-2) ---")
    print("  Loading model...")
    ppl = test_perplexity(text)
    if ppl is not None:
        classification, detail = classify_perplexity(ppl)
        print(f"  Result: {classification}")
        print(f"  {detail}")
        print(f"  Reference: AI=15-40 | Borderline=40-60 | Human=60-200+")
    else:
        print(f"  [SKIP] Could not load model")
        print(f"  Install: pip install transformers torch 'numpy<2'")

    # RoBERTa Classification
    print(f"\n--- ROBERTA CLASSIFICATION ---")
    print("  Loading model...")
    print("  (WARNING: unreliable for CVs/technical docs - see skill docs)")
    human, ai = test_roberta(text)
    if human is not None:
        print(f"  Human: {human:.1f}%  |  AI: {ai:.1f}%")
        if human < 10:
            print(f"  Score: FAILED (but this is normal for CVs - don't panic)")
        elif human < 30:
            print(f"  Score: POOR (expected for technical/structured documents)")
        elif human < 50:
            print(f"  Score: MODERATE")
        else:
            print(f"  Score: GOOD")
    else:
        print(f"  [SKIP] Could not load model")

    # Summary
    print(f"\n{'=' * 60}")
    print(f"  SUMMARY")
    print(f"{'=' * 60}")

    issues_count = 0
    if em > 0 or en > 0 or dd > 0:
        print(f"  * Fix unicode dashes/double-hyphens first")
        issues_count += 1
    if os.path.isfile(input_arg) and check_metadata(input_arg):
        print(f"  * Fix metadata fingerprints")
        issues_count += 1
    if ppl is not None and ppl < 60:
        print(f"  * Perplexity is low ({ppl:.0f}) - add more human variation")
        issues_count += 1

    if issues_count == 0:
        print(f"  Document looks good! No major issues detected.")
        if ppl and ppl > 80:
            print(f"  Perplexity ({ppl:.0f}) is solidly in human territory.")
    print()


if __name__ == '__main__':
    main()