// Russian translations for field labels and descriptions.
// Used by ru.ts instead of the English defaults from constants.ts.

export const RU_FIELD_LABELS: Record<string, string> = {
  model: 'Модель по умолчанию',
  model_context_length: 'Окно контекста',
  fallback_providers: 'Резервные модели',
  toolsets: 'Включённые наборы инструментов',
  timezone: 'Часовой пояс',
  'display.personality': 'Личность',
  'display.show_reasoning': 'Блоки рассуждений',
  'agent.max_turns': 'Макс. шагов агента',
  'agent.image_input_mode': 'Вложения изображений',
  'terminal.cwd': 'Рабочая директория',
  'terminal.backend': 'Бэкенд выполнения',
  'terminal.timeout': 'Тайм-аут команды',
  'terminal.persistent_shell': 'Постоянная оболочка',
  'terminal.env_passthrough': 'Передача переменных окружения',
  file_read_max_chars: 'Лимит чтения файла',
  'tool_output.max_bytes': 'Лимит вывода терминала',
  'tool_output.max_lines': 'Лимит страницы файла',
  'tool_output.max_line_length': 'Лимит длины строки',
  'code_execution.mode': 'Режим выполнения кода',
  'approvals.mode': 'Режим подтверждений',
  'approvals.timeout': 'Тайм-аут подтверждения',
  'approvals.mcp_reload_confirm': 'Подтверждать перезагрузку MCP',
  command_allowlist: 'Белый список команд',
  'security.redact_secrets': 'Скрывать секреты',
  'security.allow_private_urls': 'Разрешить приватные URL',
  'browser.allow_private_urls': 'Приватные URL в браузере'
}

export const RU_FIELD_DESCRIPTIONS: Record<string, string> = {
  model: 'Основная модель для ответов. Fallback-модели используются при ошибке.',
  model_context_length: 'Максимальное количество токенов в окне контекста.',
  fallback_providers: 'Дополнительные провайдеры на случай отказа основного.',
  toolsets: 'Наборы инструментов, доступные агенту.',
  timezone: 'Часовой пояс для отображения времени.',
  'display.personality': 'Файл личности (AGENTS.md / SOUL.md).',
  'display.show_reasoning': 'Показывать блоки рассуждений модели.',
  'agent.max_turns': 'Максимальное количество итераций агента за один запрос.',
  'agent.image_input_mode': 'Как обрабатывать вложенные изображения.',
  'terminal.cwd': 'Рабочая директория для команд терминала.',
  'terminal.backend': 'Где выполнять команды: локально, Docker, SSH.',
  'terminal.timeout': 'Сколько секунд ждать завершения команды.',
  'terminal.persistent_shell': 'Сохранять состояние оболочки между командами.',
  'terminal.env_passthrough': 'Какие переменные окружения передавать в терминал.',
  file_read_max_chars: 'Максимум символов при чтении файла.',
  'tool_output.max_bytes': 'Максимальный размер вывода терминала в байтах.',
  'tool_output.max_lines': 'Максимум строк на страницу вывода.',
  'tool_output.max_line_length': 'Обрезать строки длиннее этого значения.',
  'code_execution.mode': 'Как выполнять код: безопасно, с подтверждением или без ограничений.',
  'approvals.mode': 'Когда запрашивать подтверждение перед выполнением.',
  'approvals.timeout': 'Сколько ждать ответа пользователя.',
  'approvals.mcp_reload_confirm': 'Спрашивать разрешение перед перезагрузкой MCP-серверов.',
  command_allowlist: 'Команды, которые можно выполнять без подтверждения.',
  'security.redact_secrets': 'Автоматически скрывать API-ключи и пароли в выводе.',
  'security.allow_private_urls': 'Разрешить доступ к localhost и внутренним адресам.',
  'browser.allow_private_urls': 'Разрешить браузеру открывать приватные URL.'
}
