"""Docs persona profile detection and bootstrap helpers.

Provides two idempotent operations:

- ``get_docs_profile_status()`` — check whether a ``docs`` profile exists
  under the Hermes profiles root and report basic info about it.

- ``bootstrap_docs_profile()`` — create a minimal ``docs`` profile if one
  does not already exist.  Never overwrites existing files so user
  customisations are preserved.

The ``docs`` profile layout is the standard Hermes profile layout produced
by ``hermes profile create docs``.  This module reproduces only the minimum
subset needed for the Docs persona to function:

    ~/.hermes/profiles/docs/
        config.yaml       (minimal model config — not written if present)
        SOUL.md           (docs persona persona prompt — not written if present)
        memories/         (directory — created if absent)
        sessions/         (directory — created if absent)
        skills/           (directory — created if absent)
        logs/             (directory — created if absent)

All paths resolve through ``get_hermes_home()`` so multi-profile setups
remain isolated.  No OAuth, no token storage, no model calls.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

from hermes_constants import get_hermes_home

log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

DOCS_PROFILE_NAME = "docs"

# Minimum directories created inside a fresh docs profile
_PROFILE_DIRS = ["memories", "sessions", "skills", "logs"]

# Minimal config.yaml content — enough for `hermes -p docs chat` to start.
# Uses "auto" provider so the user's real credentials are picked up without
# any extra setup.  Not written when a config.yaml already exists.
_MINIMAL_CONFIG_YAML = """\
# Hermes Docs persona profile — auto-generated by hermes-docs bootstrap.
# Edit freely; this file will NOT be overwritten by subsequent bootstraps.
model:
  provider: auto
  default: ""
"""

# Minimal SOUL.md written when absent.  Intentionally brief — users are
# expected to customise this for their own workflow.
_DOCS_SOUL_MD = """\
# Hermes Docs Persona

You are the Hermes Docs assistant embedded inside Hermes Docs.

Your job is to help the user read, structure, question, and brainstorm
around their documents.  You have access to the current workspace,
active document, selected text, and workspace session history.

You do not directly modify documents.  You produce proposed comments,
suggested rewrites, outline changes, questions to ask, claims to verify,
and command drafts for the user to review and apply.
"""


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _hermes_root() -> Path:
    """Resolve the Hermes root that holds the profiles/ directory.

    get_hermes_home() returns either the default ``~/.hermes`` or a named
    profile directory.  We always want the root so we can access the shared
    ``profiles/`` sub-tree.
    """
    hermes_home = get_hermes_home()
    if hermes_home.parent.name == "profiles":
        # Already inside a named profile — grandparent is the root
        return hermes_home.parent.parent
    return hermes_home


def _docs_profile_dir() -> Path:
    """Return the expected path for the docs profile directory."""
    return _hermes_root() / "profiles" / DOCS_PROFILE_NAME


def _profile_exists(profile_dir: Path) -> bool:
    """Return True when the directory contains a config.yaml (minimal check)."""
    return (profile_dir / "config.yaml").exists()


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def get_docs_profile_status() -> dict[str, Any]:
    """Return a status dict describing the docs profile installation state.

    Return shape::

        {
            "installed": bool,           # True when profile is present
            "profile_dir": str | None,   # absolute path if installed
            "has_soul": bool,            # whether SOUL.md exists
            "has_config": bool,          # whether config.yaml exists
        }
    """
    profile_dir = _docs_profile_dir()
    installed = _profile_exists(profile_dir)
    if not installed:
        return {
            "installed": False,
            "profile_dir": None,
            "has_soul": False,
            "has_config": False,
        }
    return {
        "installed": True,
        "profile_dir": str(profile_dir),
        "has_soul": (profile_dir / "SOUL.md").exists(),
        "has_config": True,
    }


def bootstrap_docs_profile() -> dict[str, Any]:
    """Create a minimal docs profile if one does not already exist.

    Idempotent: calling this multiple times is safe.  Existing files are
    never overwritten.

    Return shape::

        {
            "status": "created" | "already_exists",
            "profile_dir": str,
            "created_files": list[str],   # paths created in this call
        }
    """
    profile_dir = _docs_profile_dir()

    created: list[str] = []

    # 1. Create profile directory and standard sub-directories
    profile_dir.mkdir(parents=True, exist_ok=True)
    if not _profile_exists(profile_dir):
        created.append(str(profile_dir))

    for subdir in _PROFILE_DIRS:
        subdir_path = profile_dir / subdir
        if not subdir_path.exists():
            subdir_path.mkdir(parents=True, exist_ok=True)
            created.append(str(subdir_path))

    # 2. Write config.yaml if absent (idempotent after first run)
    config_path = profile_dir / "config.yaml"
    if not config_path.exists():
        config_path.write_text(_MINIMAL_CONFIG_YAML, encoding="utf-8")
        created.append(str(config_path))

    # 3. Write SOUL.md if absent
    soul_path = profile_dir / "SOUL.md"
    if not soul_path.exists():
        soul_path.write_text(_DOCS_SOUL_MD, encoding="utf-8")
        created.append(str(soul_path))

    log.info(
        "docs profile bootstrapped at %s (%d items created)",
        profile_dir,
        len(created),
    )
    return {
        "status": "already_exists" if _profile_exists(profile_dir) and str(config_path) not in created else "created",
        "profile_dir": str(profile_dir),
        "created_files": created,
    }
