#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════
# Video Pipeline Setup — Fixture Product Teaser
#
# Generated by kanban-video-orchestrator skill.
#
# Slug:      fixture-product-teaser
# Workspace: ~/projects/video-pipeline/fixture-product-teaser
# Tenant:    fixture-product-teaser
# ═══════════════════════════════════════════════════════════════════════
set -euo pipefail

PROJECT_SLUG="fixture-product-teaser"
WORKSPACE="$HOME/projects/video-pipeline/${PROJECT_SLUG}"
TENANT="fixture-product-teaser"

# ─────────────────────────────────────────────────────────────────────
# 1. Verify required API keys
# ─────────────────────────────────────────────────────────────────────
echo "═══ Checking required API keys ═══"

check_key() {
    local var="$1"
    local kc_account="${2:-hermes}"
    local kc_service="${3:-$1}"
    if grep -q "^${var}=" "$HOME/.hermes/.env" 2>/dev/null && \
       [ -n "$(grep "^${var}=" "$HOME/.hermes/.env" | cut -d= -f2-)" ]; then
        echo "  ✓ ${var} (env)"
        return 0
    fi
    if command -v security >/dev/null 2>&1 && \
       security find-generic-password -a "${kc_account}" -s "${kc_service}" -w >/dev/null 2>&1; then
        echo "  ✓ ${var} (Keychain ${kc_account}/${kc_service})"
        return 0
    fi
    echo "  ✗ ${var} not set in ~/.hermes/.env or Keychain (${kc_account}/${kc_service})"
    return 1
}

# Customize this list per project — only check keys actually used:
# (no API keys required)

# ─────────────────────────────────────────────────────────────────────
# 2. Create project workspace
# ─────────────────────────────────────────────────────────────────────
echo "═══ Creating project workspace ═══"
mkdir -p "$WORKSPACE"/{taste,audio/{voiceover,sfx},assets,scenes,checkpoints,tools,output}
mkdir -p "$WORKSPACE/scenes/scene-01"/checkpoints
mkdir -p "$WORKSPACE/scenes/scene-02"/checkpoints
echo "  ✓ $WORKSPACE"

# ─────────────────────────────────────────────────────────────────────
# 3. Create Hermes profiles
# ─────────────────────────────────────────────────────────────────────
echo "═══ Creating Hermes profiles ═══"

hermes profile create director --clone 2>/dev/null || true
hermes profile create ascii-renderer --clone 2>/dev/null || true
hermes profile create editor --clone 2>/dev/null || true
hermes profile create reviewer --clone 2>/dev/null || true

# ─────────────────────────────────────────────────────────────────────
# 4. Configure profiles (toolsets, skills, cwd)
# ─────────────────────────────────────────────────────────────────────
echo "═══ Configuring profiles ═══"

configure_profile() {
    local profile="$1"
    local toolsets_json="$2"     # JSON array string, e.g. '["kanban","terminal","file"]'
    local skills_json="$3"       # JSON array string, e.g. '["kanban-worker","ascii-video"]'
    python3 - "$profile" "$toolsets_json" "$skills_json" "$WORKSPACE" <<'PY'
"""Patch a Hermes profile config.yaml using PyYAML so we don't depend on the
exact default-config string format. Validates the patch took effect and exits
non-zero if anything's off."""
import json
import os
import sys

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML required. pip install pyyaml", file=sys.stderr)
    sys.exit(1)

profile, toolsets_json, skills_json, workspace = sys.argv[1:5]
toolsets = json.loads(toolsets_json)
skills = json.loads(skills_json)

p = os.path.expanduser(f"~/.hermes/profiles/{profile}/config.yaml")
if not os.path.exists(p):
    print(f"  ✗ profile config not found: {p}", file=sys.stderr)
    sys.exit(1)

with open(p) as f:
    cfg = yaml.safe_load(f) or {}

# Apply our changes — only the keys we actually want to set.
cfg["toolsets"] = toolsets
cfg.setdefault("skills", {})
cfg["skills"]["always_load"] = skills

# Note: we do NOT touch cfg["approvals"] — that's a security-sensitive
# setting (manual confirmation of tool calls). Workspace cwd is overridden
# per-task by `--workspace dir:<path>` on `hermes kanban create`, so we
# don't need to mutate cfg["terminal"]["cwd"] either.

with open(p, "w") as f:
    yaml.safe_dump(cfg, f, sort_keys=False)

# Validate
with open(p) as f:
    after = yaml.safe_load(f)
errors = []
if after.get("toolsets") != toolsets:
    errors.append(f"toolsets mismatch: {after.get('toolsets')!r}")
if after.get("skills", {}).get("always_load") != skills:
    errors.append(f"skills.always_load mismatch: {after.get('skills', {}).get('always_load')!r}")
if errors:
    print(f"  ✗ {profile}: " + "; ".join(errors), file=sys.stderr)
    sys.exit(1)
PY
    if [ $? -ne 0 ]; then
        echo "  ✗ failed to configure ${profile}" >&2
        exit 1
    fi
    echo "  ✓ ${profile}"
}

configure_profile 'director' '["kanban", "terminal", "file"]' '["kanban-orchestrator"]'
configure_profile 'ascii-renderer' '["terminal", "file"]' '["ascii-video"]'
configure_profile 'editor' '["terminal", "file"]' '[]'
configure_profile 'reviewer' '["terminal", "file"]' '[]'

# ─────────────────────────────────────────────────────────────────────
# 5. Write SOUL.md per profile
# ─────────────────────────────────────────────────────────────────────
echo "═══ Writing profile personalities ═══"

cat > "$HOME/.hermes/profiles/director/SOUL.md" <<'SOUL_EOF'
# director

You are the **director** for this video production.

## Project context

- **Brief:** read `brief.md` in your CWD
- **Team graph:** read `TEAM.md` in your CWD
- **Style spec:** read `taste/brand-guide.md` and `taste/emotional-dna.md` in
  your CWD

## What you do

decompose the video into specialist tasks without executing renderer work

## Inputs you read

brief.md, TEAM.md, taste/

## Outputs you produce

kanban child tasks for each specialist

## Tools and skills available

- **Toolsets:** kanban, terminal, file
- **Skills loaded:** kanban-orchestrator
- **External APIs / CLIs:** ffmpeg, ffprobe (via terminal)

## Rules

_(see TEAM.md and brief.md)_

- **Read the brief and team graph** before doing anything else.
- **Pass `workspace_kind="dir"` and `workspace_path` on every `kanban_create` call.** This keeps the team in one shared workspace.
- **Use tenant `fixture-product-teaser`** on every kanban call.
- **Write outputs to predictable paths.** Other profiles depend on your filename conventions.
- **Emit heartbeats** during long-running work. Renderers should report frame counts; editors should report assembly progress.
- **Do not execute the work yourself.** For every concrete task, create a kanban task and assign it to the appropriate profile.
- **Decompose, route, comment, approve — that's the whole job.**
- **Read TEAM.md** for the canonical task graph. Do not invent new roles unless the brief truly demands it.
- **Load the `kanban-orchestrator` skill** for the deeper decomposition playbook beyond the auto-injected baseline.


## Common reference commands

```bash
# Inspect a clip
ffprobe -v quiet -show_entries format=duration -show_entries stream=codec_name,width,height,r_frame_rate <file.mp4>

# Extract a frame for QA
ffmpeg -y -i <input.mp4> -vf "select='eq(n,30)'" -vsync vfr <out.png>
```

SOUL_EOF
echo "  ✓ SOUL.md for director"
cat > "$HOME/.hermes/profiles/ascii-renderer/SOUL.md" <<'SOUL_EOF'
# renderer-ascii

You are the **renderer-ascii** for this video production.

## Project context

- **Brief:** read `brief.md` in your CWD
- **Team graph:** read `TEAM.md` in your CWD
- **Style spec:** read `taste/brand-guide.md` and `taste/emotional-dna.md` in
  your CWD

## What you do

render the title card and product beat as deterministic ASCII frames

## Inputs you read

brief.md, TEAM.md, scenes/scene-01/

## Outputs you produce

scenes/scene-01/clip.mp4 and checkpoints

## Tools and skills available

- **Toolsets:** terminal, file
- **Skills loaded:** ascii-video
- **External APIs / CLIs:** ffmpeg, ffprobe (via terminal)

## Rules

_(see TEAM.md and brief.md)_

- **Read the brief and team graph** before doing anything else.
- **Pass `workspace_kind="dir"` and `workspace_path` on every `kanban_create` call.** This keeps the team in one shared workspace.
- **Use tenant `fixture-product-teaser`** on every kanban call.
- **Write outputs to predictable paths.** Other profiles depend on your filename conventions.
- **Emit heartbeats** during long-running work. Renderers should report frame counts; editors should report assembly progress.


## Common reference commands

```bash
# Inspect a clip
ffprobe -v quiet -show_entries format=duration -show_entries stream=codec_name,width,height,r_frame_rate <file.mp4>

# Extract a frame for QA
ffmpeg -y -i <input.mp4> -vf "select='eq(n,30)'" -vsync vfr <out.png>
```

SOUL_EOF
echo "  ✓ SOUL.md for ascii-renderer"
cat > "$HOME/.hermes/profiles/editor/SOUL.md" <<'SOUL_EOF'
# editor

You are the **editor** for this video production.

## Project context

- **Brief:** read `brief.md` in your CWD
- **Team graph:** read `TEAM.md` in your CWD
- **Style spec:** read `taste/brand-guide.md` and `taste/emotional-dna.md` in
  your CWD

## What you do

assemble rendered scenes into the final video artifact

## Inputs you read

scene clips and audio assets

## Outputs you produce

output/final.mp4 and validation notes

## Tools and skills available

- **Toolsets:** terminal, file
- **Skills loaded:** (none)
- **External APIs / CLIs:** ffmpeg, ffprobe (via terminal)

## Rules

_(see TEAM.md and brief.md)_

- **Read the brief and team graph** before doing anything else.
- **Pass `workspace_kind="dir"` and `workspace_path` on every `kanban_create` call.** This keeps the team in one shared workspace.
- **Use tenant `fixture-product-teaser`** on every kanban call.
- **Write outputs to predictable paths.** Other profiles depend on your filename conventions.
- **Emit heartbeats** during long-running work. Renderers should report frame counts; editors should report assembly progress.


## Common reference commands

```bash
# Inspect a clip
ffprobe -v quiet -show_entries format=duration -show_entries stream=codec_name,width,height,r_frame_rate <file.mp4>

# Extract a frame for QA
ffmpeg -y -i <input.mp4> -vf "select='eq(n,30)'" -vsync vfr <out.png>
```

SOUL_EOF
echo "  ✓ SOUL.md for editor"
cat > "$HOME/.hermes/profiles/reviewer/SOUL.md" <<'SOUL_EOF'
# reviewer

You are the **reviewer** for this video production.

## Project context

- **Brief:** read `brief.md` in your CWD
- **Team graph:** read `TEAM.md` in your CWD
- **Style spec:** read `taste/brand-guide.md` and `taste/emotional-dna.md` in
  your CWD

## What you do

verify artifact duration, resolution, and brief compliance

## Inputs you read

output/final.mp4, brief.md, TEAM.md

## Outputs you produce

review.md with pass/fail findings

## Tools and skills available

- **Toolsets:** terminal, file
- **Skills loaded:** (none)
- **External APIs / CLIs:** ffmpeg, ffprobe (via terminal)

## Rules

_(see TEAM.md and brief.md)_

- **Read the brief and team graph** before doing anything else.
- **Pass `workspace_kind="dir"` and `workspace_path` on every `kanban_create` call.** This keeps the team in one shared workspace.
- **Use tenant `fixture-product-teaser`** on every kanban call.
- **Write outputs to predictable paths.** Other profiles depend on your filename conventions.
- **Emit heartbeats** during long-running work. Renderers should report frame counts; editors should report assembly progress.


## Common reference commands

```bash
# Inspect a clip
ffprobe -v quiet -show_entries format=duration -show_entries stream=codec_name,width,height,r_frame_rate <file.mp4>

# Extract a frame for QA
ffmpeg -y -i <input.mp4> -vf "select='eq(n,30)'" -vsync vfr <out.png>
```

SOUL_EOF
echo "  ✓ SOUL.md for reviewer"

# ─────────────────────────────────────────────────────────────────────
# 6. Copy brief, TEAM.md, and any provided assets
# ─────────────────────────────────────────────────────────────────────
echo "═══ Writing brief + taste ═══"

cat > "$WORKSPACE/brief.md" <<'BRIEF_EOF'
# Video Brief — Fixture Product Teaser

> Slug: `fixture-product-teaser` · Tenant: `fixture-product-teaser` · Project workspace: `~/projects/video-pipeline/fixture-product-teaser`

## 1. Concept

**One-line pitch.** A tiny deterministic teaser used to validate the video orchestration skill.

**Emotional north star.** clear, mechanical, safe
*(What should the viewer feel walking away?)*

## 2. Scope

| | |
|---|---|
| Duration | 12 seconds |
| Aspect ratio | 16:9 |
| Resolution | 1280x720 |
| Frame rate | 24 fps |
| Target platforms | internal test fixture |
| Deadline | none |
| Quality bar | fixture-valid *(rough draft / polished / archival)* |

## 3. Style

**Visual references.** monospace title card

**Tone.** crisp

**Brand constraints.** none
*(colors, typography, motion language; or "n/a")*

**Aesthetic rules.**
deterministic text outputs only

## 4. Scenes

Beat-by-beat breakdown. Each scene gets a row.

| # | Time | Content | Target tool / skill | Audio | Notes |
|---|------|---------|---------------------|-------|-------|
| 1 | 0:00-0:06 | ASCII title card: Fixture Product Teaser | ascii-renderer | soft launch sting | deterministic fixture scene |
| 2 | 0:06-0:12 | Product silhouette resolves into call to action | ascii-renderer | resolve sting | same renderer for fixture simplicity |

## 5. Audio

**Approach.** silent fixture with placeholder cues
*(narration / music-only / synced to track / silent / mixed)*

**Voiceover.** n/a
*(provider, voice, language, script source — "n/a" if no VO)*

**Music.** n/a
*(provided track path / commission via Suno / commission via heartmula /
license-free / "n/a")*

**SFX.** text cues only
*(generated, library, or "n/a")*

## 6. Deliverables

| Format | Resolution | Notes |
|--------|-----------|-------|
| mp4 | 1280x720 | The main output |
| _(none)_ |  |  |

**Final filename.** `output/final.mp4`
*(plus optional `output/final-9x16.mp4`, `output/captions.srt`, etc.)*

## 7. Constraints

- API keys required: none
- External dependencies: Python 3.11+
- Source assets to incorporate: none

---

**This brief is the contract. The director and every downstream profile read
it. If the brief changes, the kanban must be re-fired — don't edit live.**

BRIEF_EOF

cat > "$WORKSPACE/TEAM.md" <<'TEAM_EOF'
# Team & Task Graph — Fixture Product Teaser

## Team

- `director` — decompose the video into specialist tasks without executing renderer work (loads `kanban-orchestrator`)
- `ascii-renderer` — render the title card and product beat as deterministic ASCII frames (loads `ascii-video`)
- `editor` — assemble rendered scenes into the final video artifact (no skills required)
- `reviewer` — verify artifact duration, resolution, and brief compliance (no skills required)

## Task Graph

```
T0  director — decompose
T1    ascii-renderer — scene 1: ASCII title card: Fixture Product Teaser (parents: T0)
T2    ascii-renderer — scene 2: Product silhouette resolves into call to action (parents: T0)
T3    editor — assemble + mux (parents: T1, T2)
T4    reviewer — final QA (parent: T3)
```

## Per-task workspace requirement

All `kanban_create` calls MUST pass:
```
workspace_kind="dir"
workspace_path="$HOME/projects/video-pipeline/fixture-product-teaser"
tenant="fixture-product-teaser"
```
TEAM_EOF

cat > "$WORKSPACE/taste/brand-guide.md" <<'TASTE_EOF'
# Brand Guide

_(Populate with project-specific colors, typography, motion rules)_
TASTE_EOF
cat > "$WORKSPACE/taste/emotional-dna.md" <<'DNA_EOF'
# Emotional DNA

_(What this piece should FEEL like — populate from the brief.)_
DNA_EOF

# Add cp/rsync commands here for any provided assets

# ─────────────────────────────────────────────────────────────────────
# 7. Fire the initial kanban task
# ─────────────────────────────────────────────────────────────────────
echo "═══ Firing initial kanban task ═══"

hermes kanban create "Direct production of Fixture Product Teaser" \
    --assignee director \
    --workspace dir:"$WORKSPACE" \
    --tenant "$TENANT" \
    --priority 2 \
    --max-runtime 4h \
    --body "$(cat <<EOF
Read brief.md, TEAM.md, and taste/.

Decompose into the team graph defined in TEAM.md.

All child tasks MUST use:
  workspace_kind="dir"
  workspace_path="$WORKSPACE"
  tenant="$TENANT"

Do not execute the work yourself — route every concrete subtask to the
appropriate profile via kanban_create.
EOF
)"

echo ""
echo "═══ Setup complete ═══"
echo ""
echo "Monitor with:"
echo "  hermes kanban watch --tenant $TENANT"
echo "  hermes kanban list  --tenant $TENANT"
echo "  hermes dashboard"
echo ""
echo "Workspace: $WORKSPACE"
